### ISSUE TITLE
Openpay doesn't appear in Extensions on Opencart 3.0.2

### ISSUE THREAD

**Issue by RASA911216** [open-pay/openpay-opencart#1]
Hello, I'm trying to integrate Openpay in an Opencart website and tried to follow the instructions given in the [openpay website](https://www.openpay.mx/docs/plugins/opencart.html).

So far I've managed to install the extension and Opencart shows it in the installed section. The problem comes when trying to to go Extensions -> Payments and try to activate the Openpay modules, they don't appear in the application.

I'm running Opencart 3.0.2, is there something different I must do?

And if it isn't compatible with Opencart 3, would there be a way to embed the Openpay module using pure HTML/Javascript?

Thanks in advance!

**Comment by veerubolem** [comment]
Same issue here, it is appearing as "heading_title" when I try to install so many errors showing. This is not compatible version for 3.xxxx.

**Comment by fedebalderas** [comment]
We are working on it :)
