### ISSUE TITLE
Error openpay_cards.php Notice: Undefined property: stdClass::$status

### ISSUE THREAD

**Issue by UnexpectedObject** [open-pay/openpay-opencart#10]
Hola.

Tengo instalado los modulos de Bancos, Tarjetas y Tiendas en modo SandBox, y solicite una validación del sitio para pasar a modo Producción, pero el revisor técnico encontró el error que adjunto en la imagen, por lo tanto el sitio no paso la prueba.

En los logs del Dashboard, la única prueba fallida es usando el método de tarjetas, pero me informa el revisor que también mediante SPEI falla, pero no hay registro de ello.

¿Alguna idea de que puede ser?

La imagen en cuestión:
![1574729393334re](https://user-images.githubusercontent.com/21160055/70359939-bd3cad80-1842-11ea-9eac-ff482321c064.png)

De antemano gracias.

**Comment by fedebalderas** [comment]
@UnexpectedObject que versión del plugin tienes instalada? Porque esa línea si checas el código del repositorio no se hace ninguna referencia a una variable "status": https://github.com/open-pay/openpay-opencart/blob/2d38119aa7651c91fbee0eb91be3572eb932ea12/openpay_cards/catalog/controller/extension/payment/openpay_cards.php#L215

Adicional a ello, que versión de OpenCart utilizas?

**Comment by UnexpectedObject** [comment]
@fedebalderas Uso la versión 2.0 del plugin, de la fecha 22 de Octubre. Tengo instala la versión 3.0.2.0 de OpenCart.

Logre replicar el error, este se da cuando hago las pruebas con los Números de tarjeta no validos que aparece en la documentación de OpenPay.
Todas dan el mismo error, excepto la MasterCard, que como bien dice la documentación es aprobada en 3D Secure.
El error aparece justo después del SIMULADOR 3D SECURE, una vez ingresada la clave de acceso.

El error es:
`Notice: Undefined property: stdClass::$status in /home4/joakin19/centromakita.com/catalog/controller/extension/payment/openpay_cards.php on line 220Notice: Undefined property: stdClass::$status in /home4/joakin19/centromakita.com/catalog/controller/extension/payment/openpay_cards.php on line 644Notice: Undefined property: stdClass::$status in /home4/joakin19/centromakita.com/catalog/controller/extension/payment/openpay_cards.php on line 649Notice: Undefined property: stdClass::$status in /home4/joakin19/centromakita.com/catalog/controller/extension/payment/openpay_cards.php on line 658Warning: Cannot modify header information - headers already sent by (output started at /home4/joakin19/centromakita.com/catalog/controller/startup/error.php:34) in /home4/joakin19/centromakita_opencart/modification/system/library/response.php on line 36`

Los logs de Openpay muestra correctos la creación de los Tokens, Cliente y del cargo. También en los eventos, muestran como cargos fallidos(es el resultado esperado) las pruebas, por lo que está bien.

De antemano muchas gracias.

**Comment by UnexpectedObject** [comment]
El error se manifiesta cuando se hace uso de una tarjeta invalida(provistas en la documentación) al tratar de confirmar el cargo con el Secure 3D.
Al momento de crear el objeto cargo, el webservice de Openpay devuelve un objeto diferente al que espera recibir.
El objeto que espera recibir debe contener la propiedad **status**, pero en cambio el objeto que recibe solo contiene la propiedad **error**.
Cuando trata de hacer la verificación de **status** es donde sucede el error.
Solo hay que añadir otra condición que se encargue de verificar el objeto que devuelve esta linea:
`$charge = $this->getOpenpayCharge` , y agregar la propiedad **status** como _failed_.
