### ISSUE TITLE
Openpay Stores y Openpay Banks no aparecen en el módoulo de pago

### ISSUE THREAD

**Issue by raulsan16** [open-pay/openpay-opencart#11]
Tengo un problema, ya instale y configure ambas extensiones, pero no me aparecen en el front de la tienda, es como si no estuviera activa. pero toda la configuración se hizo conforme al manual.

como dato, si me aparece el cobro con tarjeta, pero no los otros 2 metodos.

gracias por su amable ayuda

**Comment by fedebalderas** [comment]
@raulsan16 probablemente sea por el tipo de moneda que tienes configurado en tu tienda (dólares tal vez). Bancos (SPEI) y pago en tienda únicamente funciona con pesos mexicanos.

Saludos!

**Comment by raulsan16** [comment]
Gracias, si era eso!
