### ISSUE TITLE
Compatible con Opencart 3.0.2 ?

### ISSUE THREAD

**Issue by ninjaxallen** [open-pay/openpay-opencart#2]
Hola, es compatible con la versión Opencart 3.0.2 ?

**Comment by fedebalderas** [comment]
@ninjaxallen @UnexpectedObject la última actualización del plugin esta probada sobre la versión 3.0.2.0 de Opencart, pueden descargar los ZIP de aquí: https://github.com/open-pay/openpay-opencart/tree/master/openpay_opencart_plugin_3.0
