### ISSUE TITLE
Extenciones Opencart 2.0.3.1

### ISSUE THREAD

**Issue by ghost** [open-pay/openpay-opencart#3]
Intente instalar la extencion, pero al intentar ver el enlace de pagos para configurar la extencion la seccion de pagos desaparece por completo.

¿alguna idea de porque el problema?

**Comment by fedebalderas** [comment]
@ktwrra,  estas realizando la instalación localmente o ya en un servidor público?

**Comment by ktwrra** [comment]
lo estoy realizando local

**Comment by fedebalderas** [comment]
@ktwrra y no te marca algún error sobre FTP? Porque al menos para la versión 2.X de Opencart la instalación de extensiones utiliza por default FTP algo que localmente no esta configurado por lo general.

En caso de que presentes este problema, revisa este artículo https://isenselabs.com/posts/how-to-solve-opencart-2-issue-when-ftp-support-is-disabled , yo te recomiendo que utilices la opción de **"Developer version"**

De cualquier modo para validar si se instalo la extensión, deberías de tener los archivos .php del plugin ya en tu proyecto, por poner un ejemplo, revisa si tienes este archivo en el directorio de tu proyecto: 

> admin/controller/payment/openpay_cards.php

**Comment by ktwrra** [comment]
si ya instale el FIX del FTP, y todo sube correctamente el detalle es que algo ocasiona la instalación y el enlace de pagos ya no muestra nada solo el NOT FOUND 404
