### ISSUE TITLE
Error en Twig

### ISSUE THREAD

**Issue by dieg15** [open-pay/openpay-opencart#4]
Que tal, con ansias esperando esta librería para OpenCart 3.0.2.0, gracias por el desarollo.
Te informo que en los Twigs de las librerías están mal las rutas de los archivos:
` <link rel="stylesheet" type="text/css" href="/catalog/view/theme/default/stylesheet/openpay_cards.css">`

Debería ser:
` <link rel="stylesheet" type="text/css" href="catalog/view/theme/default/stylesheet/openpay_cards.css">`

Eso es en todas las rutas. 

De ahí en fuera no he encontrado otro detalle. Nuevamente agradezco mucho el desarrollo.

Saludos.

**Comment by fedebalderas** [comment]
@dieg15 Gracias por el dato, lo revisamos y actualizamos. Cualquier cosa seguimos pendientes.
