### ISSUE TITLE
Error con redirección?

### ISSUE THREAD

**Issue by ArmandoValencia** [open-pay/openpay-opencart#6]
Me salta el siguiente error cuando intento realizar un cargo con openpay en opencart 

`{"redirect":false,"error":"Missing token"}`

Sin embargo no hay un campo donde se pueda ingresar una pagina de redirección en el plugin.

**Comment by fedebalderas** [comment]
@ArmandoValencia sería de mucha ayuda si nos comentas que versión del plugin tienes, que versión de Opencart tienes y como tienes configurado el plugin en tu backoffice porfa.

Saludos!

**Comment by ArmandoValencia** [comment]
Instalé el plugin en su versión 3.0 (la que está fuera de carpetas) a través del instalador de extensiones de opencart, solo tengo cargadas las claves de prueba de sandbox. Activada la extensión y activado el Test mode. 

Se carga bien el plugin pero al realizar un intento de compra con una de las tarjetas de prueba pej. 4111111111111111 al enviar el formulario me regresa una pantalla en blanco con el texto 

`{"redirect":false,"error":"Missing token"}`

La versión de opencart es 3.0.2.0

**Comment by fedebalderas** [comment]
@ArmandoValencia y la configuración de la pestaña "Configuración de los cargos" como la tienes? De igual forma podrías ayudarme a validar si las peticiones están llegando a Openpay, es decir, revisar el log desde el dashboard de tu cuenta de Openpay.

**Comment by ArmandoValencia** [comment]
Title: Openpay Tarjetas
Geo Zone 
Status: Habilitado
Total: $100
Sort Order:
Months: 
¿Cómo procesar el cargo? : Directo
Configuración del cargo: Cargo Inmediato
Pago con puntos  NO
Guardar tarjetas  NO

Estatus: Canceled


En el  Customer Orders Report no se registra el movimiento cuando se utiliza openpay, pero sí si se selecciona el pago con paypal. Tampoco aparece el movimiento en la consola de pedidos.

**Comment by fedebalderas** [comment]
@ArmandoValencia pero ese error es con respecto a la creación del webhook, esta se dispara cuando se guarda la configuración del módulo de tiendas. Pero al momento de tratar de hacer un cargo se registra algún log en Openpay? Has revisado tus logs de tu tienda? Porque en realidad el único redireccionamiento que a mi me preocuparía sucede pero es cuando se tiene habilitado el 3D Secure, por eso te pedía la info de como tenías tu configuración.

Traté de revisar tu página pero no me resuelve.

**Comment by ArmandoValencia** [comment]
Tienes razón, el log de error no coincide con los intentos de pago, más allá de eso no se ha registrado nada en el log de openpay. El 3D Secure, no sé qué sea, por lo que podría ir por allí la tirada. 

La pagina está resolviendo correctamente, tal vez hubo algún pico de tráfico o algo.

**Comment by ArmandoValencia** [comment]
Hola me ayudan, no he podido activar el plugin de Open Pay en OpenCart 3, me sigue mandando el siguiente error al querer realizar el pago con alguna de las tarjetas de prueba:

{"redirect":false,"error":"Missing token"}

Solamente tengo registradas en la configuración lo siguiente
Test Mode:   Yes
Test Merchant ID : xxle1s8t2nlkfbxxxxxx
Test Secret Key : sk_xx0a552db88d4948a48a6ed223fxxxxxx
Test Public Key: pk_xx7e0b70958c4017a49e38f45xxxxxx

(Escondo algunos carácteres) Los datos los saque del dashboard de Sandbox de openpay.

En configuración del cargo lo he intentado en directo y con 3D secure y cargo inmediato y todo me resuelve el mismo error. No me loggea nada de actividad dentro de openpay y tampoco en el dashboard de opencart: basculaselectronicas.com

También intenté agregar la libreria de openpay.js al header de mi pagina ya que no veía ningún archivo similar y tampoco tuve suerte. No sé qué estoy haciendo mal, no debería de ser tan difícil con el plugin.
