### ISSUE TITLE
Fatal error: Call to a member function getOrder() on a non-object 

### ISSUE THREAD

**Issue by deltha07** [open-pay/openpay-opencart#7]
Buen día, estoy tratando de integrar OpenPay en mi sitio con Opencart 3.0.2.0 y el tema Journal 3.0.37, instalé los tres módulos y el módulo de Tiendas de conveniencia me funciona perfecto, pero con los otros dos módulos estoy teniendo las siguientes dificultades...

1. Al momento de introducir los accesos para el módulo OpenPay Tarjetas me aparece el mensaje de que los datos han sido modificados exitosamente, pero en la parte del front office (en la pag de checkout) me aparece el siguiente código de error en donde se supone deberían mostrarse las tarjetas con las que se puede pagar:

`Fatal error: Call to a member function getOrder() on a non-object in /home/user/mydomain.com/catalog/controller/extension/payment/openpay_cards.php on line 67`

---

2. Por otra parte, en el módulo OpenPay Bancos, al momento de guardar las configuraciones me aparece el siguiente mensaje:

`Notice: Trying to get property of non-object in /home/user/mydomain.com/admin/controller/extension/payment/openpay_banks.php on line 25Warning: Cannot modify header information - headers already sent by (output started at /home/user/mydomain.com/admin/controller/startup/error.php:34) in /home/user/mydomain_opencart/modification/system/library/response.php on line 36`

A pesar de esto, el módulo parece funcionar bien, se muestra correctamente en el front office y genera el recibo de pago, pero no se si este detalle afecte de alguna manera algun otro proceso.

Agradezco mucho de antemano su atención y su ayuda.

**Comment by fedebalderas** [comment]
@deltha07 recién subimos unos cambios al repositorio, ya se que quieras descargar e instalar nuevamente o aplicarlos manualmente.

https://github.com/open-pay/openpay-opencart/commit/2b8268876a8272503053d2042fa0aa080054e123#diff-8549473951bba2ca06aca5975cc3e939

Me dices como te fue.

**Comment by deltha07** [comment]
Muchas gracias, parece ser que ya funciona todo correctamente con el módulo de tarjetas. Únicamente me queda la inquietud del módulo de bancos, ¿afecta de alguna manera el warning que me aparece después de guardar configuraciones? Aparentemente todo funciona bien (tanto en el front office así como en mi cuenta Sandbox de Openpay), se generan los recibos, re realizan los pedidos y los pagos se ven reflejados.

**Comment by fedebalderas** [comment]
@deltha07 Creo que esta relacionado con que ya esta creado el webhook en tu cuenta de Openpay, lo cual es bueno, sin emabrgo cada que se da "Guardar" se intenta crear nuevamente. De hecho si pudieras verificar que los webhooks están creados y verificados en Openpay porfa, solo para tener el dato. 

Esto lo puedes verificar desde tu dashboard de Openpay en la esquina superior derecha donde esta el engrane (Configuración), por ahí debe de haber un apartado de webhooks.

**Comment by deltha07** [comment]
Oh sí, efectivamente tengo creados los webhooks para openpay_banks y openpay_stores, gracias por la ayuda.
