### ISSUE TITLE
Problema al configurar una cuenta nueva de Openpay

### ISSUE THREAD

**Issue by deltha07** [open-pay/openpay-opencart#8]
Buen día, realicé la integración de los 3 módulos de Openpay en mi sitio y todo funcionaba muy bien dentro del ambiente de pruebas. Ahora cambié el id y las llaves para ligar mi sitio a una cuenta de Openpay nueva (es una cuenta sandbox que después pasaré a producción), el problema es que una vez configurada la cuenta nueva me arroja el siguiente error:

`Notice: Undefined property: stdClass::$id in /home/user/mydomain.com/catalog/controller/extension/payment/openpay_stores.php on line 309{"error":"The customer with id 'charges' does not exist"}`

El error ocurre en el lado del front office cuando trato de confirmar un pedido con cualquiera de los 3 métodos de pago.

Si vuelvo a configurar mi sitio con el id y las llaves de la cuenta antigua me anda muy bien, el problema surge cuando trato de configurar una cuenta distinta.

Gracias de antemano

**Comment by fedebalderas** [comment]
@deltha07 podrías intentar un flujo de compra con un usuario nuevo de tu tienda y ver si te funciona?

**Comment by deltha07** [comment]
Me funcionó, gracias por la ayuda.
