### ISSUE TITLE
Problema al realizar compra como invitado

### ISSUE THREAD

**Issue by deltha07** [open-pay/openpay-opencart#9]
Buen día, se me ha presentado el siguiente problema: Al realizar una compra en mi sitio (spei o paynet) como Invitado, el sistema me redirige correctamente y me genera el recibo pdf pero en la parte superior me aparece el siguiente Notice

`Notice: Undefined index: guest in /home/user/mydomain.com/catalog/controller/extension/payment/openpay_banks.php on line 163Notice: Undefined index: guest in /home/user/mydomain.com/catalog/controller/extension/payment/openpay_banks.php on line 163`

Adicional a esto, en mi dashboard la compra se registra con los datos del **primer usuario invitado** con el que hice una compra en mi sitio y no con los datos del usuario que estoy introduciendo al realizar la compra. De igual manera en el pdf aparecen los datos del **primer usuario invitado** y no los del que realmente hizo la compra. 

Veo que Openpay  está realizando cambios en su sistema en general y no se si este problemilla tenga que ver con el plugin o con la api, agradezco su ayuda y su pronta respuesta.

**Comment by fedebalderas** [comment]
@deltha07 Acabamos de subir una actualización de los plugins, crees que pudieras instalar las nuevas versiones (de los plugins que utilices) y realizar pruebas nuevamente?

Quedo al pendiente de tus comentarios.


Saludos!
